### ISSUE TITLE
Google Analytics Tracking Pixel

### ISSUE THREAD

**Issue by streeetlamp** [streeetlamp/Postman#1]
Give this a whirl  
http://dyn.com/blog/tracking-email-opens-via-google-analytics/

**Comment by streeetlamp** [comment]
This is more difficult than I thought it would be. Gmail now serves images via their own servers so tracking pixels are busted. Bananatags requires the email to be actually sent via the gmail client or allow it to access your mail servers.

**Comment by luetkemj** [comment]
![](http://i.imgur.com/BNwlm.gif)

**Comment by streeetlamp** [comment]
not gonna happen !
